## Домашнее задание - Библиотека numpy

Подпишите этот блокнот: укажите ФИО и номер группы. Выполненное задание загрузите в свой репозиторий «<b>Python_Introduction_2022</b>» в github 

Перед выполнением этого домашнего задания полезно прочитать про возможности и основные методы библиотеки numpy:  
http://acm.mipt.ru/twiki/bin/view/Cintro/PythonNumpy  


1.	Создайте равномерное разбиение интервала от -1.3 до 2.5 на 64 отрезка.

In [2]:
import numpy as np

shift = (1.3 + 2.5)/64.0
a = np.arange(-1.3, 2.5, shift)
print(a)


[-1.3      -1.240625 -1.18125  -1.121875 -1.0625   -1.003125 -0.94375
 -0.884375 -0.825    -0.765625 -0.70625  -0.646875 -0.5875   -0.528125
 -0.46875  -0.409375 -0.35     -0.290625 -0.23125  -0.171875 -0.1125
 -0.053125  0.00625   0.065625  0.125     0.184375  0.24375   0.303125
  0.3625    0.421875  0.48125   0.540625  0.6       0.659375  0.71875
  0.778125  0.8375    0.896875  0.95625   1.015625  1.075     1.134375
  1.19375   1.253125  1.3125    1.371875  1.43125   1.490625  1.55
  1.609375  1.66875   1.728125  1.7875    1.846875  1.90625   1.965625
  2.025     2.084375  2.14375   2.203125  2.2625    2.321875  2.38125
  2.440625]


2.	Сгенерируйте numpy массив длины $3n$, заполненный циклически числами 1, 2, 3, 1, 2, 3, 1....

In [13]:

b = np.array([])
n = 13
for i in range(3*n):
    b = np.append(b, 1 + i%3)
print(b)

[1. 2. 3. 1. 2. 3. 1. 2. 3. 1. 2. 3. 1. 2. 3. 1. 2. 3. 1. 2. 3. 1. 2. 3.
 1. 2. 3. 1. 2. 3. 1. 2. 3. 1. 2. 3. 1. 2. 3.]


3.	Создайте массив первых 10 нечетных целых чисел.

In [22]:
a3 = np.array([])
for i in range (10):
    a3 = np.append(a3, 1 + 2*i)
print(a3)
    
    

[ 1.  3.  5.  7.  9. 11. 13. 15. 17. 19.]


4.  Создайте массив нулей размера 10 x 10, а затем создайте в нём "рамку" из единиц по краям.

In [34]:
a4 = np.zeros((10,10))
print(a4)
print('\n')
for j in range(10):
    a4[0,j]=1
    a4[9,j]=1
    a4[j,0]=1
    a4[j,9]=1
print(a4)


[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


5.  Создайте массив 8 x 8 с шахматной доской из нулей и единиц.

In [46]:
a5 = np.zeros((8,8))
for i in range (8):
    for j in range (8):
        if (i+j)%2 == 1:
            a5[i,j] = 1
    
    
print(a5)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


6.  Создайте функцию, которая создает $n×n$ матрицу с $(i,j)$-элементом, равным $i+j$.

In [48]:
n = 6
a6 = np.zeros((n,n))
for i in range (n):
    for j in range (n):
        a6[i,j] = i+j
    
print(a6)

[[ 0.  1.  2.  3.  4.  5.]
 [ 1.  2.  3.  4.  5.  6.]
 [ 2.  3.  4.  5.  6.  7.]
 [ 3.  4.  5.  6.  7.  8.]
 [ 4.  5.  6.  7.  8.  9.]
 [ 5.  6.  7.  8.  9. 10.]]


7. Примените функцию dot для перемножения вектор на вектор, матрицу на вектор и матрицу на матрицу.

In [3]:
A = np.ones((3,3))
x = np.array([1,2,3])
print(np.dot(A,x))
y = np.array([2, -1, 0])
print (np.dot(x,y))
B = np.array([y,y,y])
print (np.dot(B,A))


[6. 6. 6.]
0
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


8. Вычислите cos(x) и sin(x) на интервале [0,1] с шагом $0.05$, а затем объедините оба массива чисел как строки в один массив.

In [58]:
a8 = np.arange(0,1,0.05)
for i in a8:
    a8 = np.cos(a8)
b8 = np.arange(0,1,0.05)
for i in b8:
    b8 = np.sin(b8)
    
c8 = np.append(a8,b8)
print(c8)

[0.73893776 0.73893844 0.73894049 0.73894392 0.73894873 0.73895493
 0.73896253 0.73897153 0.73898193 0.73899369 0.73900678 0.73902114
 0.7390367  0.73905332 0.73907087 0.73908919 0.73910806 0.73912726
 0.73914656 0.73916569 0.         0.04958827 0.09681871 0.13983724
 0.17757071 0.20971494 0.23653338 0.25860943 0.27664526 0.29133441
 0.30329781 0.31306129 0.32105593 0.32762846 0.33305499 0.33755435
 0.34129981 0.34442873 0.34705035 0.34925179]


9. Создайте матрицу $A$ размера $3×5$ из случайных чисел с равномерным распределением на отрезке $[-1,3]$ (используйте np.random.rand)

In [4]:
A = np.random.rand(3,5)
A = 4*A - 1

print(A)

[[ 2.54585237  0.98661538  2.97214126  1.79741075  2.46821285]
 [ 1.64369344  0.08371399 -0.83709811  2.38031333  0.98316841]
 [ 0.41793353  2.14078406 -0.91449495  1.22179341 -0.32188376]]


10. Найдите сумму всех элементов, сумму внутри строк, сумму внутри столбцов, а также среднее значение, дисперсию и стандартное отклонение чисел для каждой строки матрицы $A$. (Подобно тому, как sorted имеет необязательный аргумент key=, многие функции Numpy имеют необязательный аргумент axis=)


In [12]:
sum = 0
for number in A:
    sum += number
print('sum = ', np.sum(A))
print( 'the sum of 1, 2, 3 rows is equal to ', np.sum(A[0]), np.sum(A[1]), np.sum(A[2])) #сумма строк

A = np.transpose(A)
print( 'the sum of 1, 2, 3, 4, 5 collums is equal to ')

for i in range (5):     #сумма столбцов
    print(np.sum(A[i]))
    
print('\n')
    
A = np.transpose(A) 

for i in range(3):    #среднее строк
    print(np.mean(A[i]))
    
print("\n variance: \n")

for i in range (3):      #дисперсия
    print (np.var(A[i]))

    print("\nstandard deviation: \n")
    
for i in range (3):
    print (np.std(A[i]))


sum =  17.568155933946002
the sum of 1, 2, 3 rows is equal to  10.77023260366132 4.253791049514755 2.5441322807699263
the sum of 1, 2, 3, 4, 5 collums is equal to 
4.607479328932002
3.2111134309307596
1.2205481923579402
5.399517484714261
3.129497497011038


2.154046520732264
0.8507582099029509
0.5088264561539853

 variance: 

0.48231516562231247

 standard deviation: 

1.2846066786736983

 standard deviation: 

1.179158459154737

 standard deviation: 

0.6944891400319464
1.1334049049980763
1.0858906294626256


11.  Отнимите от каждого элемента матрицы $A$ среднее по строке и поделите на стандартное отклонение строки.

In [20]:
for i in range (3):
    for j in range (5):
        A[i,j] = (A[i,j] - np.mean(A[i]))/np.std(A[i])
print(A)

[[-0.88676374 -1.33553986  0.15664396  0.6936449   1.4090449 ]
 [-0.22541081 -0.85296237 -1.15732223  1.50554952  0.77024967]
 [-0.46488483  1.15858044 -1.42303505  1.12636087 -0.38390708]]


12. Отсортируйте матрицу $A$ по 3-ому столбцу, т.е. поменяйте местами строки матрицы так, чтобы 3-й столбец оказался отсортированным. Используйте для этого slicing + argsort + indexing.

13. Посчитайте две матрицы: $B = A^TA$ и $C = AA^T$. Что вы можете о них сказать? Какого они размера? В чём их сходство и отличие?

In [26]:
B = np.dot(np.transpose(A),A)
print(B)
C = np.dot(A, np.transpose(A))
print ('\n', C)

[[ 1.05327787  0.8379688   0.78351416 -1.47809436 -1.24463996]
 [ 0.8379688   3.85352016 -0.87075251 -0.90558783 -2.98361685]
 [ 0.78351416 -0.87075251  3.38896084 -3.23660165 -0.12439546]
 [-1.47809436 -0.90558783 -3.23660165  4.01651141  1.70460791]
 [-1.24463996 -2.98361685 -0.12439546  1.70460791  2.72607673]]

 [[ 5.06110477  3.28739695 -1.11764504]
 [ 3.28739695  4.9777135   2.16356242]
 [-1.11764504  2.16356242  4.99952874]]


14. Найдите сумму диагональных элементов матриц $B$ и $C$.

In [28]:
print(np.trace(B), np.trace(C))

15.038347012898283 15.038347012898281


15.	Посчитайте детерминант и ранг матриц $A$, $B$ и $C$, посмотрите на спектр (набор собственных значений) матриц $B$ и $C$, какие выводы вы можете сделать?  
(подсказка: используйте готовые функции из библиотеки np.linalg). 


In [ ]:
print(np.linalg.det(A))
print(np.linalg.det(B))
print(np.linalg.det(C))
print(np.linalg.matrix_rank(A),np.linalg.eigh(A))
print(np.linalg.matrix_rank(B),np.linalg.eigh(B))
print(np.linalg.matrix_rank(C),np.linalg.eigh(C))

16. Численно посчитать определённый интеграл  3-мя методами:  
a)	Прямоугольников $\int\limits_a^b {f(x)dx \approx \Delta x\sum\limits_{k = 0}^N {f({x_k})} }$  
b)	Трапеций $\int\limits_a^b {f(x)dx \approx \frac{{\Delta x}}{2}\left( {f({x_0}) + 2\sum\limits_{k = 1}^{N - 1} {f({x_k})}  + f({x_N})} \right)}$  
c)	По правилу Симпсона  $\int\limits_a^b {f(x)dx \approx \frac{{\Delta x}}{3}\left( {f({x_0}) + 2\sum\limits_{k = 1}^{N/2 - 1} {f({x_{2k}})}  + 4\sum\limits_{k = 1}^{N/2} {f({x_{2k - 1}})}  + f({x_N})} \right)}$  


В реализации этих методов цикл for для суммирования использовать нельзя.  
Нужно посчитать значение интеграла с некоторым шагом интегрирования (например начать с 0.1), потом уменьшить его в десять раз и ещё раз посчитать и так до тех пор пока отличие в ответах будет в 5-м знаке после запятой, т.е. чтобы ошибка была меньше 1e-5. Получить ответы для 3-х разных методов и сделать соответствующие выводы.  

Далее необходимо сравнить полученные оценки с аналитическим решением (т.е. формульным, которое вы должны сами посчитать на листочке и вбить формулу-ответ).   

В качестве интеграла взять один из следующих с номером, сгенерированным случайным образом с помощью функции np.random.randint(10), в качестве seed для генератора случайных чисел взять номер своего студенческого билета.

<table width="80%"
       align="center">
    <tr>
        <td> 0) $\int\limits_3^4 {\frac{{{x^2} + 3}}{{x - 2}}dx}$ </td>
        <td> 1) $\int\limits_{ - 2}^{ - 1} {\frac{{x + 1}}{{{x^3} - {x^2}}}dx}$ </td>
        <td> 2) $\int\limits_1^2 {\frac{{{e^{1/{x^2}}}}}{{{x^3}}}dx}$ </td>
        <td> 3) $\int\limits_1^e {\frac{{\cos (\ln x)}}{x}dx}$ </td>
        <td> 4) $\int\limits_1^e {\frac{{dx}}{{x(1 + {{\ln }^2}x)}}}$ </td>
    </tr>                
    <tr>
        <td> 5) $\int\limits_0^{\pi /2} {{{\cos }^3}\alpha \;d\alpha }$ </td>
        <td> 6) $\int\limits_0^{1/3} {c{h^2}3x\;dx}$ </td>
        <td> 7) $\int\limits_2^3 {\frac{{dy}}{{{y^2} - 2y - 8}}dy}$ </td>
        <td> 8) $\int\limits_{3/4}^2 {\frac{{dx}}{{\sqrt {2 + 3x - 2{x^2}} }}}$ </td>
        <td> 9) $\int\limits_0^2 {\frac{{2x - 1}}{{2x + 1}}dx}$ </td>
        </tr>
</table>

In [66]:
np.random.seed(1032216507)
np.random.randint(10)

ans = 2 - np.log(5)
print("true value = ", ans, "\n")


dx_1 = 0.1 
dx_2 = 0.01
dx_2 = 0.001
dx_3 = 0.0001
dx_4 = 0.00001
dx_5 = 0.000001

def f(x):
    return ((2*x - 1) / (2*x + 1))

g = np.vectorize(f)
# first method
    #first try
print ("thirst ************************\n")

a = g(np.arange(0, 2, dx_1))
res_1 = (a.sum() * dx_1)
#print (res_1)
print ("dx = 0.1 difference = ",np.abs(ans - res_1), "\n" )


a = g(np.arange(0, 2, dx_3))
res_3 = (a.sum() * dx_3)
#print (res_3)
print ("dx = 0.001 difference = ",np.abs(ans - res_3), "\n" )

     #success
a = g(np.arange(0, 2, dx_4))
res_4 = (a.sum() * dx_4)
#print (res_3)
print ("dx = 0.00001 difference = ",np.abs(ans - res_4), "\n" )


#second method 
print ("second ************************\n")
a = g(np.arange(0, 2, dx_1))
res_1 = (dx_1/2)*( a[0] + a [-1] + 2*(a.sum() - a[0] - a[-1]))
print ("dx = 0.1 difference = ",np.abs(ans - res_1), "\n" )

a = g(np.arange(0, 2, dx_3))
res_3 = (dx_3/2)*( a[0] + a [-1] + 2*(a.sum() - a[0] - a[-1]))
print ("dx = 0.001 difference = ",np.abs(ans - res_3), "\n" )

a = g(np.arange(0, 2, dx_4))
res_4 = (dx_4/2)*( a[0] + a [-1] + 2*(a.sum() - a[0] - a[-1]))
print ("dx = 0.00001 difference = ",np.abs(ans - res_4), "\n" )


# third method 
print ("third ************************\n")
a = g(np.arange(0, 2, dx_1))
odd = a.reshape(-1, 2)[:,1]
even = a.reshape(-1, 2)[:,0]
res_1 = (dx_1/3)*(a[0] + a[-1] + 2*(even.sum() - even[0] - even[-1]) + 4*(odd.sum() ))
print ("dx = 0.1 difference = ",np.abs(ans - res_1), "\n" )

a = g(np.arange(0, 2, dx_3))
odd = a.reshape(-1, 2)[:,1]
even = a.reshape(-1, 2)[:,0]
res_3 = (dx_3/3)*(a[0] + a[-1] + 2*(even.sum() - even[0] - even[-1]) + 4*(odd.sum() ))
print ("dx = 0.001 difference = ",np.abs(ans - res_3), "\n" )

a = g(np.arange(0, 2, dx_4))
odd = a.reshape(-1, 2)[:,1]
even = a.reshape(-1, 2)[:,0]
res_4 = (dx_4/3)*(a[0] + a[-1] + 2*(even.sum() - even[0] - even[-1]) + 4*(odd.sum() ))
print ("dx = 0.00001 difference = ",np.abs(ans - res_4), "\n" )



true value =  0.3905620875658997 

thirst ************************

dx = 0.1 difference =  0.08318693198607319 

dx = 0.001 difference =  8.000320000001171e-05 

dx = 0.00001 difference =  8.00003199996624e-06 

second ************************

dx = 0.1 difference =  0.06235359865273987 

dx = 0.001 difference =  6.0002399968062115e-05 

dx = 0.00001 difference =  6.0000239999191685e-06 

third ************************

dx = 0.1 difference =  0.03828559155875355 

dx = 0.001 difference =  3.9998399850693644e-05 

dx = 0.00001 difference =  3.999983999802836e-06 

